# NumPy
#### NumPy(Numerical Python):　科学や数学のための数値計算ライブラリ

In [1]:
# NumPy import　※　np　として使用すると宣言する
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## NumPy Arrays(ndarray)
#### アレイズ, エヌディアレイ　
##### 行列は普通２Dのイメージだが、3D,　4D　と次元をもった　Arrays(配列)

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

#### ベクトルのイメージ（1次元） x軸に１、y軸に２、z軸に３

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#### Ndarray : NumPy　では　Ndarray を使用して計算していく
### かなり重要な　object　なので必ず覚える

In [9]:
matrix[0][0]

1

In [10]:
type(matrix[0][0])

numpy.int64

#### python　の　int とは違うモノ。NumPy　の numpy.int64 という data型
#### NumPy　の　Ndarray　は　NumPy　独自の　data型だという事を忘れずに覚える！！

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [12]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

#### 上記のようにして data型を変える事もできる。 data type = dtype よく使用する

In [13]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + - integer 8bit

#### 2の８乗　=　256 (0~255まで)　：　一般的な画像　data　を扱う場合にこの形式を使う

In [14]:
ndarray

array([1, 2, 3], dtype=uint8)

In [15]:
ndarray = np.array([1, 2, 3], dtype=np.float32)

In [16]:
ndarray

array([1., 2., 3.], dtype=float32)

#### dtype=float32 : 機械学習に使う　data　を保存する時によく使用する
##### 64bit　だと大きすぎる。逆に　integer　だと　data　数が足りなすぎる

In [17]:
ndarray = np.array([1, 2, 3], dtype=np.float64)

In [18]:
ndarray

array([1., 2., 3.])

#### 見た目は一緒だが、中のメモリを倍確保できるので data を細かく扱う事ができる
##### 64bit　だと結構大きくなってしまうので、保存には向かない
##### dtype=float64 : 実際のモデル学習には64bitで学習することが多い

In [20]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

#### .astype()で元の ndarray　の dtype　を変更できる