# np.arange(), np.linspace(), np.logspace()

- <u>NumPy が持っている関数を使用して、　array を作成する事ができる</u>

## np.arange( )
- **( start= 0, stop, step= 1 )**
    - *start 以上、 stop未満の要素を step 間隔に作成*
    - *stop と step は省力可能。その場合 start=0, step=1 が入る*

In [2]:
import numpy as np

In [3]:
np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [7]:
list(range(2, 15, 4))

[2, 6, 10, 14]

In [8]:
np.arange(10, 1, -1)  # 降順に並べることができる

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

## np.linspace( )
- **( start=0, stop, num=50 )**
    - *start以上　stop以下の数を　num個で区切った値を出力*
    - stopを含むので注意

In [11]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## np.logspace( )
- **( start, stop, num=50 )**
    - *10** start以上 10** stop以下の数を　num個で区切った数を出力*

In [13]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

- 1 ~ 1000 までの数字を　10個の数値を取ってくる
    - **1 ~ 1000 までの数字を　１０等分しているわけではんない**


- <u>1 ~ 1000 の数字を１０等分した数値を累乗している</u>

In [17]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [18]:
10 ** 0.3333333

2.154434524672917

- linspace( ), logspace( ), は endpoint=False という引数で　stopの数字を以下ではなく **未満**　で結果を出力可能

In [21]:
np.linspace(0, 3, 10, endpoint=False)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [22]:
np.logspace(0, 3, 10, endpoint=False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])