# NumPy Array の条件 filter の使用

In [2]:
import numpy as np

## np.clip( )
- **np.clip( a, a_min, a_max )**
    - *最小値を最大値を設定する*
        - 設定した範囲以外の数字は最小値、最大値を適用する

In [4]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

- <u>0 に限りなく近付く関数の時に使用する</u>
    - log(0.00000000....)　->　という風になってしまうと ->　**-inf (infinitely)**　:　無限 になってしまう
    - **-inf**　が　bug　の元になる
        - *そういう場合に何処かの値で　np.clip(　)　をする*

In [6]:
1e-4 

0.0001

## numpy array の condition

In [8]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.where
- **np.where( condition, a, b)**
    - *condition が　True　の要素は　a　に、　False　の要素には　b　に置き換わる*

In [16]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [17]:
np.where(array > 3, 'a', 'b')

array(['b', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [18]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

- <u>condition だけを指定すると、条件に一致する index が返される</u>

In [19]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- 各要素に毎に適用される

In [21]:
# filterの役割を果たしている
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

- 一旦　boolean で　filter　を作成して
    - そこから要素を取り出す


- <u>where　と　array は返す値が違うので注意する</u>

In [23]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

- tuple型で帰ってくる

In [28]:
(result,) = np.where(array > 3)  # ( )括弧は省略できるが、　tuple型とわかるように記述 : unpacking される

In [29]:
result

array([4, 5, 6, 7, 8, 9])

In [30]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

- **ndarray[ condition ]**
    - *ndarray　を　filter　する時は、　where　より一般的にこちらを利用する*
    

In [31]:
ndarray = array.reshape(2, 5)

In [32]:
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

- <u>filter をかけたら　フラットで返ってくるので注意する</u>

In [35]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [37]:
(ndarray > 3).all()

False

- **( condition ).all( )**
    - *ndarray 全ての要素が　condition を満たすかを判定*

In [39]:
(ndarray > 3).any()

True

- **( condition ).any( )**
    - *ndarray　の要素内、どれか一つでも　condition　を満たしているかを判定*

In [40]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

- all( ) の引数に　axis = 0 を入れることによって　**各列毎に評価してくれる**
    - axis = 1 行も同じく

In [41]:
(ndarray > 3).all(axis=1)

array([False,  True])

In [43]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

## np.unique( )
- **重複要素を除いた結果を出力する**

In [46]:
array = np.array([1, 1, 2, 3, 4, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 3, 4, 5])

In [47]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [48]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 1, 2, 2, 1]))

- 各　label　の要素がどのくらいあるのか？結果を出力してくれる

## np.bincount( )
- 0, 1, 2, 3... の各カウント数を返す
    - *0から連番の数を数えてくれる*
        - **値がないものでも　0　という形で結果を出力してくれる**

In [50]:
np.bincount(array)

array([0, 2, 1, 2, 2, 1])