# Broadcastion (ブロードキャスティング)
- 要素数が一致しなくても、自動で補って計算してくれる

## ndarray の演算

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- ndarray の演算は各要素毎

In [12]:
a = [1, 2, 3]
b = [1, 2, 3]

In [13]:
a + b

[1, 2, 3, 1, 2, 3]

In [14]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

- 普通の list は要素毎の演算はできない

In [19]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [20]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [21]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Broadcastion (ブロードキャスティング)
- 要素数が一致しなくても、自動で補って計算してくれる

In [23]:
ndarray2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
ndarray2 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
a = [1, 2, 3]
b = 3

In [26]:
a + 3

TypeError: can only concatenate list (not "int") to list

- list では計算できない
    - python のlist は　list どうしを結合するモノなので、結合できない