# 結合と転置
- np.concatenate( )
- np.stack( )

In [1]:
import numpy as np

In [2]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [4]:
ndarray_odd = np.arange(1, 18, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

## concatenate( )

In [5]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

- 縦に結合される

In [6]:
np.concatenate([ndarray_even, ndarray_odd], axis=0)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

- default は　0　で列結合（縦の結合）　:　axis=1 は行(横結合)

In [7]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

## np.stack( )
- concatenate( ) より頻繁に使用される

In [8]:
np.stack([ndarray_even, ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [10]:
_

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

#### 戻り値を入れ忘れた時は　_(アンダースコア)に最後の戻り値が入っているのでそれを変数に代入する

In [11]:
stacked_array = _

In [14]:
stacked_array.shape

(2, 3, 3)

In [15]:
stacked_array = np.stack([ndarray_even, ndarray_odd], axis=1)
stacked_array

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]],

       [[12, 14, 16],
        [13, 15, 17]]])

In [16]:
stacked_array.shape

(3, 2, 3)

In [19]:
stacked_array = np.stack([ndarray_even, ndarray_odd], axis=-1)
stacked_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [20]:
stacked_array.shape

(3, 3, 2)

### np.concatenate( ) と np.stack( ) の違い
- **np.concatenate( )**
    - 二次元配列
        - [ **高さ, 横**  ]
        - [ 0, 1 ]
 

- **np.stack( )**
    - 三次元配列
        - [ **高さ, 横, 奥行き** ]
        - [ 0, 1, 2 or -1 ]


- <u>2次元 (rank:2)</u>
    - *白黒画像*
        - **高さ, 横**


- <u>3次元 (rank:3)</u>
    - *カラー画像*
        - **高さ, 横, 奥行き**


- <u>4次元 (rank:4)</u>
    - *カラー画像が複数枚ある*
        - **個数, 高さ, 横, 奥行き**


- <u>NumPyでは…</u>
    - 次元の数を　**rank(ランク)**　とも呼ぶ

### np.transpose.T
- 行と列を入れ替えてくれる関数

In [21]:
ndarray = np.random.randn(3, 4)
ndarray

array([[-0.73662668,  0.99791128,  0.18366101,  0.40067401],
       [ 0.56418414,  2.07094217,  0.5167148 ,  0.6547747 ],
       [ 1.77309944,  0.68620562, -1.29108781, -0.7447182 ]])

In [22]:
ndarray.shape

(3, 4)

In [23]:
np.transpose(ndarray)

array([[-0.73662668,  0.56418414,  1.77309944],
       [ 0.99791128,  2.07094217,  0.68620562],
       [ 0.18366101,  0.5167148 , -1.29108781],
       [ 0.40067401,  0.6547747 , -0.7447182 ]])

In [24]:
transpose_ndarray = _

In [25]:
transpose_ndarray.shape

(4, 3)

In [26]:
ndarray.T

array([[-0.73662668,  0.56418414,  1.77309944],
       [ 0.99791128,  2.07094217,  0.68620562],
       [ 0.18366101,  0.5167148 , -1.29108781],
       [ 0.40067401,  0.6547747 , -0.7447182 ]])

In [27]:
ndarray

array([[-0.73662668,  0.99791128,  0.18366101,  0.40067401],
       [ 0.56418414,  2.07094217,  0.5167148 ,  0.6547747 ],
       [ 1.77309944,  0.68620562, -1.29108781, -0.7447182 ]])

In [28]:
ndarray = np.random.randn(3, 4, 5)

In [30]:
ndarray.T.shape

(5, 4, 3)

In [31]:
ndarray = np.random.randn(3)

In [32]:
ndarray

array([ 0.58804378, -1.04219967, -0.2431332 ])

In [33]:
ndarray.T

array([ 0.58804378, -1.04219967, -0.2431332 ])

In [34]:
np.transpose(ndarray)

array([ 0.58804378, -1.04219967, -0.2431332 ])