# Indexing と Slicing

In [2]:
import numpy as np

In [4]:
ndarray = np.array([1, 2, 3, 4])

In [5]:
ndarray

array([1, 2, 3, 4])

In [6]:
ndarray[0]

1

In [7]:
ndarray[-1]

4

In [8]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
ndarray[0]

array([1, 2])

In [10]:
ndarray[0][1]

2

In [11]:
ndarray[0, 1]

2

- [ 行, 列 ]　の index で取得できる

### 次元について ( rank )
- <u>2次元 (rank:2)</u>
    - *白黒画像*
        - [ **高さ, 横** ]


- <u>3次元 (rank:3)</u>
    - *カラー画像*
        - [ **高さ, 横, 奥行き** ]


- <u>4次元 (rank:4)</u>
    - *カラー画像が複数枚ある*
        - [ **個数, 高さ, 横, 奥行き** ]


- <u>NumPyでは…</u>
    - 次元の数を　**rank(ランク)**　とも呼ぶ

## Slicing

In [12]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [13]:
ndarray[1:3]

array([2, 3])

### [　N : M　] 　->　N 以上 M 未満を返す

In [14]:
ndarray[:3]

array([1, 2, 3])

In [15]:
ndarray[1:]

array([2, 3, 4])

In [16]:
ndarray[-2]

3

In [17]:
ndarray[-2:]

array([3, 4])

In [18]:
ndarray[:-2]

array([1, 2])

In [19]:
ndarray[:]

array([1, 2, 3, 4])

### : (コロン)　が index を省略しているイメージ

In [20]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
ndarray.shape

(4, 4)

In [25]:
ndarray[:3]  # 行のindex ３未満

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
ndarray[:3, 2:]  # 行が３未満、列が２以上　の index を取得

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### [ 行 , 列 ]　の順番

In [29]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])

In [30]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- ndarray[ :3 ] をした配列に対してまた ndarray[ 2: ] のスライスをしている事になる
     - **常に行に対してしか slicing できていない**


#### <u>基本的には [ 行 , 列 ] の使い方が一般的なのでこちらで覚える</u>