# 行列の生成
- **np.zeros( )**
    - *要素が全て 0 の　ndarray*
    
    
- **np.ones( )**
    - *要素が全て 1 の ndarray*
    
    
- **np.eye( )**
    - *対角要素が全て 1 の ndarray*

In [1]:
import numpy as np

### np.zeros( shape )

In [2]:
shape =(3, 4)  # numpy の shape は tuple形式で操作
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros(3)  # shape の引数に tuple ではなく　 int(integer) を入れると、　一列の配列ができる（一次元配列）

array([0., 0., 0.])

- **np.zeros( )**
    - *事前に ndarray の箱(入れ物)を作成しておく*用途で使用される
        - 後から中身を書き換えていって ndarray を作成していく形が一般的

### np.ones( shape )

In [5]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((5, 4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

- zeros と使用の仕方は同じ
    - *default の値をセットするのかしないのか？*の違い

### np.eye( )
- N * N の単位行列
    - 単位行列とは対角成分が全て１の正方行列のこと

In [8]:
# I : identify matrix(単位行列)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])