# 乱数の生成　:　np.random

In [2]:
import numpy as np

### np.random.rand( )
- 0 ~ 1.0 の間で毎回違う値が生成される

In [6]:
np.random.rand()

0.5225455340231491

In [7]:
np.random.rand(3, 4)

array([[0.21491733, 0.51586219, 0.12033378, 0.77711372],
       [0.49519684, 0.47159362, 0.32836671, 0.55850876],
       [0.8031839 , 0.96275206, 0.88756175, 0.8457144 ]])

- programing で生成される乱数は<u>本当の意味でランダムな数値ではない</u>


- *programing の世界ではロジックに従って推測できない数値を乱数という*


#### 擬似乱数　pseudo random
- <u>AI, 機械学習, 深層学習, ニューラルネットワーク</u>
    - **ほとんどの場合は「 擬似乱数 」**で構わない(問題ない)


- *どういった場合に本当の乱数が必要になるのか？*
    - **セキュリティー**などのコンピューターscience
        - それ以外はほとんど必要ない

## np.random.seed
- np.random.seed( )
    - seed を指定すると、毎回同じ乱数を生成してくれる


- <u>再現性のあるcodeを記述できる</u>

In [10]:
np.random.seed(1)
np.random.rand()

0.417022004702574

- <u>乱数生成には基本的には seed を使う</u>
    - **作成した　model や成果物を再現する事ができるから**

In [11]:
np.random.rand()

0.7203244934421581

## np.random.randn( )
- **正規分布**
    - 自然界の何かの分布、身長など etc...


- **標準正規分布**
    - 平均が　0　、分散が　1 の時


- <u>標準正規分布からランダムに値を取得してくるのが　np.random.randn( )</u>

In [12]:
# 標準正規分布(平均　０, 分散 1)からランダムに値が返される
np.random.randn()

-0.5281717522634557

In [13]:
np.random.randn(2, 3)

array([[-1.07296862,  0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ,  0.3190391 ]])

In [14]:
np.random.randn(10, 10)

array([[-0.24937038,  1.46210794, -2.06014071, -0.3224172 , -0.38405435,
         1.13376944, -1.09989127, -0.17242821, -0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918,  1.14472371,  0.90159072,  0.50249434,
         0.90085595, -0.68372786, -0.12289023, -0.93576943, -0.26788808],
       [ 0.53035547, -0.69166075, -0.39675353, -0.6871727 , -0.84520564,
        -0.67124613, -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218],
       [ 0.74204416, -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,
         0.05080775, -0.63699565,  0.19091548,  2.10025514,  0.12015895],
       [ 0.61720311,  0.30017032, -0.35224985, -1.1425182 , -0.34934272,
        -0.20889423,  0.58662319,  0.83898341,  0.93110208,  0.28558733],
       [ 0.88514116, -0.75439794,  1.25286816,  0.51292982, -0.29809284,
         0.48851815, -0.07557171,  1.13162939,  1.51981682,  2.18557541],
       [-1.39649634, -1.44411381, -0.50446586,  0.16003707,  0.87616892,
         0.31563495, -2.02220122, -0.30620401

- *０　から離れるにあたって、出力される確率が低くなる*
    - 上記を見ても分かるように、　0.〇〇　という数値が多い。　１　とか　２　は少ない

### 標準正規分布
- <u>任意の平均と標準偏差の正規分布から擬似乱数を生成</u>

In [16]:
np.random.normal(0, 1) # 0 に近い値が出る

-1.3731173202467557

In [18]:
np.random.normal(10, 1) # 10 に近い値が出る

10.846160647585034

## np.random.randint()
- **( low , high=None, size=None)**
    - <u>low 以上　high 未満のランダムな整数で size の　ndarray 生成</u>

In [20]:
np.random.randint(10, 100, (2, 3))

array([[44, 42, 29],
       [77, 34, 93]])

|- ２行、３列の各要素が　１０　以上　１００未満の数をランダムに生成

In [22]:
np.random.randint(10)

6

- <u>*low* だけ指定すると</u>
    - **high　=　None の場合は, 0　以上　low　未満の値**が返される

## np.random.choice( )
- <u>指定した ndarray(list) からランダムな値を取得してくる</u>

In [25]:
a = [1, 2, 3]
np.random.choice(a)

2

In [26]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [34]:
np.random.choice(index_pool)

4