# Shape

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

- 上記は broadcastiong 可能な ndarray

In [5]:
array1 = np.array([[1, 2]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (1,2) (3,3) 

#### ndarray を作成して一番最初にする事　=　shape を確認する

In [7]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])

In [8]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
ndarray.shape

(3, 2)

- tuple 型で帰ってくる
    - 3行・2列の形

In [11]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
ndarray.reshape(1, 3)

ValueError: cannot reshape array of size 6 into shape (1,3)

- サイズが合わないから
    - 3 * 2 = 6 の元の　array　に対して 1 * 3 = 3 に　**reshape**　はできない

In [13]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [14]:
ndarray1

array([1, 2, 3])

In [16]:
print(ndarray1.shape)

(3,)


In [19]:
for i in ndarray1:
    print(i)

1
2
3


In [20]:
ndarray2

array([[1, 2, 3]])

In [21]:
print(ndarray2.shape)

(1, 3)


In [22]:
for i in ndarray2:
    print(i)

[1 2 3]


### 行列とは
- <u>複数の行があって、複数の列がある</u>


- *ndarray1 は行列になっていない*
    - **ベクトルの形**　行列ではない

- *ndarray2 は行列*
    - **1行・3列の行列**